//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4_BrianLiang_Web.WebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Incident", Namespace="http://schemas.datacontract.org/2004/07/Lab4_BrianLiang")]
    [System.SerializableAttribute()]
    public partial class Incident : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateClosedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOpenedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IncidentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TechIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateClosed {
            get {
                return this.DateClosedField;
            }
            set {
                if ((this.DateClosedField.Equals(value) != true)) {
                    this.DateClosedField = value;
                    this.RaisePropertyChanged("DateClosed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOpened {
            get {
                return this.DateOpenedField;
            }
            set {
                if ((this.DateOpenedField.Equals(value) != true)) {
                    this.DateOpenedField = value;
                    this.RaisePropertyChanged("DateOpened");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IncidentID {
            get {
                return this.IncidentIDField;
            }
            set {
                if ((this.IncidentIDField.Equals(value) != true)) {
                    this.IncidentIDField = value;
                    this.RaisePropertyChanged("IncidentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TechID {
            get {
                return this.TechIDField;
            }
            set {
                if ((this.TechIDField.Equals(value) != true)) {
                    this.TechIDField = value;
                    this.RaisePropertyChanged("TechID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceReference.IIncidentService")]
    public interface IIncidentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetAllIncidents", ReplyAction="http://tempuri.org/IIncidentService/GetAllIncidentsResponse")]
        Lab4_BrianLiang_Web.WebServiceReference.Incident[] GetAllIncidents(int techID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetAllIncidents", ReplyAction="http://tempuri.org/IIncidentService/GetAllIncidentsResponse")]
        System.Threading.Tasks.Task<Lab4_BrianLiang_Web.WebServiceReference.Incident[]> GetAllIncidentsAsync(int techID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetAllCustIncidents", ReplyAction="http://tempuri.org/IIncidentService/GetAllCustIncidentsResponse")]
        Lab4_BrianLiang_Web.WebServiceReference.Incident[] GetAllCustIncidents(int custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetAllCustIncidents", ReplyAction="http://tempuri.org/IIncidentService/GetAllCustIncidentsResponse")]
        System.Threading.Tasks.Task<Lab4_BrianLiang_Web.WebServiceReference.Incident[]> GetAllCustIncidentsAsync(int custID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetCustomerID", ReplyAction="http://tempuri.org/IIncidentService/GetCustomerIDResponse")]
        Lab4_BrianLiang_Web.WebServiceReference.Incident[] GetCustomerID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIncidentService/GetCustomerID", ReplyAction="http://tempuri.org/IIncidentService/GetCustomerIDResponse")]
        System.Threading.Tasks.Task<Lab4_BrianLiang_Web.WebServiceReference.Incident[]> GetCustomerIDAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIncidentServiceChannel : Lab4_BrianLiang_Web.WebServiceReference.IIncidentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IncidentServiceClient : System.ServiceModel.ClientBase<Lab4_BrianLiang_Web.WebServiceReference.IIncidentService>, Lab4_BrianLiang_Web.WebServiceReference.IIncidentService {
        
        public IncidentServiceClient() {
        }
        
        public IncidentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IncidentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncidentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncidentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Lab4_BrianLiang_Web.WebServiceReference.Incident[] GetAllIncidents(int techID) {
            return base.Channel.GetAllIncidents(techID);
        }
        
        public System.Threading.Tasks.Task<Lab4_BrianLiang_Web.WebServiceReference.Incident[]> GetAllIncidentsAsync(int techID) {
            return base.Channel.GetAllIncidentsAsync(techID);
        }
        
        public Lab4_BrianLiang_Web.WebServiceReference.Incident[] GetAllCustIncidents(int custID) {
            return base.Channel.GetAllCustIncidents(custID);
        }
        
        public System.Threading.Tasks.Task<Lab4_BrianLiang_Web.WebServiceReference.Incident[]> GetAllCustIncidentsAsync(int custID) {
            return base.Channel.GetAllCustIncidentsAsync(custID);
        }
        
        public Lab4_BrianLiang_Web.WebServiceReference.Incident[] GetCustomerID() {
            return base.Channel.GetCustomerID();
        }
        
        public System.Threading.Tasks.Task<Lab4_BrianLiang_Web.WebServiceReference.Incident[]> GetCustomerIDAsync() {
            return base.Channel.GetCustomerIDAsync();
        }
    }
}
